---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scipy-notebook
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.first: /notebook/kubeflow-user/scipy
    serviceaccounts.openshift.io/oauth-redirectreference.first: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"scipy-notebook"}}'
