apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- route.yaml
namespace: notebook-controller-ui
commonLabels:
  app: jupyter-web-app
  kustomize.component: jupyter-web-app
