apiVersion: v1
kind: Service
metadata:
  labels:
    run: jupyter-web-app
  name: service
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: jupyter-web-app-tls
spec:
  ports:
  - name: oauth-proxy
    port: 443
    protocol: TCP
    targetPort: oauth-proxy
  type: ClusterIP
