apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
        - name: ose-oauth-proxy
          image: registry.redhat.io/openshift4/ose-oauth-proxy
          imagePullPolicy: IfNotPresent
          args:
            - --provider=openshift
            - --https-address=:8443
            - --http-address=
            - --client-id=system:serviceaccount:$(JWA_NAMESPACE):jupyter-web-app-service-account
            - --client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
            - --cookie-secret-file=/etc/proxy/secrets/session_secret
            - --tls-cert=/etc/tls/private/tls.crt
            - --tls-key=/etc/tls/private/tls.key
            - --upstream=http://localhost:5000
            - --upstream-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - --skip-auth-regex=^/metrics
            - --email-domain=*
          ports:
            - containerPort: 8443
              name: oauth-proxy
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /oauth/healthz
              port: oauth-proxy
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /oauth/healthz
              port: oauth-proxy
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 200m
              memory: 150Mi
            requests:
              cpu: 100m
              memory: 50Mi
          volumeMounts:
            - name: jupyter-web-app-proxy-secret
              mountPath: /etc/proxy/secrets
            - name: jupyter-web-app-tls-secret
              mountPath: /etc/tls/private
      volumes:
        - name: jupyter-web-app-proxy-secret
          secret:
            defaultMode: 420
            secretName: jupyter-web-app-proxy-config
        - name: jupyter-web-app-tls-secret
          secret:
            defaultMode: 420
            secretName: jupyter-web-app-tls
